version: '2'
services:
  collect:
    image: bencinmonitor/collect:latest
    links:
      - kafka
      - zookeeper
    restart: unless-stopped

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka:0.10.0.1
    restart: unless-stopped
    links:
      - zookeeper