version: '2'
services:
  collect:
    build: .
    ports:
      - "6800:6800"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_SCRAPED_ITEMS_TOPIC: scraped-items
      KAFKA_OCR_RESULTS_TOPIC: ocr-results

  zookeeper:
    ports:
      - 2181

  kafka:
    ports:
      - 9092
    # environment:
    #   # KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
    #   # KAFKA_ADVERTISED_HOST_NAME: "kafka"
    #   KAFKA_ADVERTISED_PORT: "9092"
    #   KAFKA_ZOOKEEPER_CONNECT: zk:2181
    #   KAFKA_CREATE_TOPICS: "scraped-items:1:1,ocr-results:1:1"
    #   # HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
    #   # 104857600
    #   # 200000000
    #   KAFKA_MESSAGE_MAX_BYTES: 200000000
    #   KAFKA_ADVERTISED_HOST_NAME: localhost
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=scraped-items:1:1,ocr-results:1:1
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock