version: '2'

volumes:
  images:

services:
  scrape_petrol:
    volumes:
      - .:/home/collect
      - images:/home/collect/data/full
    command: "./bin/run-sleep.sh scrapy crawl petrol -L DEBUG"

  scrape_omv:
    volumes:
      - .:/home/collect
      - images:/home/collect/data/full
    command: "./bin/run-sleep.sh scrapy crawl omv -L DEBUG"

  ocr_worker:
    volumes:
      - .:/home/collect
      - images:/home/collect/data/full

  rq_monitor:
    ports:
      - 9181:9181
    volumes:
      - .:/home/collect

  redis:
    ports:
      - "6379:6379"

  mongo:
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
      - "28017:28017"

  api:
    image: bencinmonitor/api
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    ports:
      - "7766:7766"
    environment:
      - DEBUG=True
      - MONGO_URL=mongodb://mongo:27017/bm
      - REDIS_URL=redis://@redis:6379/1
    restart: unless-stopped
