version: '2'

volumes:
  collect_images:
    external: true
  collect_redis_data:
    external: true
  collect_mongo_data:
    external: true

services:
  scrape_petrol:
    volumes:
      - collect_images:/home/collect/data/full
    command: "./bin/run-sleep.sh scrapy crawl petrol -L INFO"

  scrape_omv:
    volumes:
      - collect_images:/home/collect/data/full
    command: "./bin/run-sleep.sh scrapy crawl omv -L INFO"

  ocr_worker:
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - collect_images:/home/collect/data/full

  rq_monitor:
    ports:
      - 9181:9181

  redis:
    volumes:
      - collect_redis_data:/data
    ports:
      - "6379:6379"

  mongo:
    volumes:
      - collect_mongo_data:/data/db
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
      - "28017:28017"