version: '2'

services:
  scrape_petrol:
    volumes:
      - .:/home/collect
    command: "./bin/run-sleep.sh scrapy crawl petrol -L DEBUG"

  scrape_omv:
    volumes:
      - .:/home/collect
    command: "./bin/run-sleep.sh scrapy crawl petrol -L DEBUG"

  ocr_worker:
    volumes:
      - .:/home/collect

  rq_monitor:
    ports:
      - 9181:9181
    volumes:
      - .:/home/collect

  redis:
    ports:
      - "6379:6379"