version: '2'
services:
  collect:
    image: bencinmonitor/collect:latest
    links:
      - redis:redis
    depends_on:
      - redis
    environment:
      - REDIS_WORK_URL=redis://@redis:6379/0
      - REDIS_DATA_URL=redis://@redis:6379/1
    restart: unless-stopped

  redis:
    image: redis:3.0
    restart: unless-stopped