version: '2'

volumes:
  images:

services:
  scrape_petrol:
    image: bencinmonitor/collect
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
      - ocr_worker
    environment:
      - SLEEP_TIME=10
    volumes:
      - images:/home/collect/data/full
    entrypoint: "bash"
    command: "./bin/run-sleep.sh scrapy crawl petrol -L INFO"
    restart: unless-stopped

  scrape_omv:
    image: bencinmonitor/collect
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
      - ocr_worker
    environment:
      - SLEEP_TIME=10
    volumes:
      - images:/home/collect/data/full
    entrypoint: "bash"
    command: "./bin/run-sleep.sh scrapy crawl omv -L INFO"
    restart: unless-stopped

  ocr_worker:
    image: bencinmonitor/collect
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    volumes:
      - images:/home/collect/data/full
    entrypoint: "python"
    command: "-m ocr_machine.workers default"
    restart: unless-stopped

  rq_monitor:
    image: bencinmonitor/collect
    links:
      - redis:redis
    depends_on:
      - redis
    environment:
      - PYTHONIOENCODING=utf-8
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    entrypoint: "rq-dashboard"
    command: " --redis-host redis --redis-port 6379 --redis-database 0 --bind 0.0.0.0"

  redis:
    image: redis:3.2
    restart: unless-stopped

  mongo:
    image: mongo:3
